apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test2
spec:
  params:
    - name: message
      default: ""
  tasks:
    - name: security-scans
      params:
        - name: message
          value: $(params.message)
      pipelineRef:
        name: test
