---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trivy
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/test-multi.*\ trivy.*"
    pipelinesascode.tekton.dev/on-cel-expression: |-
      target_branch == "main" && "docs/***".pathChanged()
    pipelinesascode.tekton.dev/task: "[tasks/echo.yaml]"
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipelines/test.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  pipelineRef:
    name: test
  params:
    - name: message
      value: |
        {{ trigger_comment }}
        {{ repo_url }}
        {{ body }}
        {{ pac }}
        {{ headers }}
        {{ files }}
        {{ files.all }}
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
