---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trivy
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |-
      event == "pull_request" || event == "push"
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/echo.yaml]"
    pipelinesascode.tekton.dev/pipeline: "[.tekton/pipelines/test.yaml]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  pipelineSpec:
    tasks:
      - name: security-scans
        params:
          - name: message
            value: |
              ==== builtin variables ====
              event_type: {{event_type}}
              git_auth_secret: {{git_auth_secret}}
        taskRef:
          apiVersion: tekton.dev/v1beta1
          kind: Pipeline
          name: test
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
